/// Represents a message in an AI Coach conversation.
class AiCoachMessage {
  final String id;
  final String conversationId;
  final String role; // 'user' | 'assistant' | 'system'
  final String content;
  final DateTime createdAt;
  final List<dynamic> toolCalls;
  final bool isOptimistic;

  const AiCoachMessage({
    required this.id,
    this.conversationId = '',
    required this.role,
    required this.content,
    required this.createdAt,
    this.toolCalls = const [],
    this.isOptimistic = false,
  });

  bool get isUser => role == 'user';
  bool get isAssistant => role == 'assistant' || role == 'system';

  factory AiCoachMessage.fromJson(Map<String, dynamic> json) {
    return AiCoachMessage(
      id: json['id'] as String? ?? '',
      conversationId: json['conversationId'] as String? ?? '',
      role: json['role'] as String? ?? 'assistant',
      content: json['content'] as String? ?? '',
      createdAt: json['createdAt'] != null
          ? DateTime.tryParse(json['createdAt'] as String) ?? DateTime.now()
          : DateTime.now(),
      toolCalls: json['toolCalls'] as List<dynamic>? ?? [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'conversationId': conversationId,
      'role': role,
      'content': content,
      'createdAt': createdAt.toIso8601String(),
      'toolCalls': toolCalls,
    };
  }
}

/// Represents the authoritative backend AI quota status.
/// Section 10.5: Quota resets at UTC midnight.
class AiQuota {
  final int usedToday;
  final int dailyLimit;
  final int remaining;
  final DateTime resetAt;

  const AiQuota({
    required this.usedToday,
    required this.dailyLimit,
    required this.remaining,
    required this.resetAt,
  });

  bool get isExhausted => remaining <= 0;

  factory AiQuota.fromJson(Map<String, dynamic> json) {
    final rawData = json['data'] is Map<String, dynamic>
        ? json['data'] as Map<String, dynamic>
        : json;

    final limit = (rawData['dailyLimit'] as num?)?.toInt() ??
        (rawData['limit'] as num?)?.toInt() ??
        50;
    final used = (rawData['usedToday'] as num?)?.toInt() ?? 0;
    final rem = (rawData['remaining'] as num?)?.toInt() ?? (limit - used).clamp(0, limit);

    DateTime reset;
    if (rawData['resetAt'] != null) {
      reset = DateTime.tryParse(rawData['resetAt'] as String) ?? _defaultReset();
    } else {
      reset = _defaultReset();
    }

    return AiQuota(
      usedToday: used,
      dailyLimit: limit,
      remaining: rem,
      resetAt: reset,
    );
  }

  static DateTime _defaultReset() {
    final now = DateTime.now().toUtc();
    return DateTime.utc(now.year, now.month, now.day + 1);
  }

  Map<String, dynamic> toJson() {
    return {
      'usedToday': usedToday,
      'dailyLimit': dailyLimit,
      'remaining': remaining,
      'resetAt': resetAt.toIso8601String(),
    };
  }
}

/// Proactive AI Coach nudge.
class AiCoachNudge {
  final String type; // 'overload' | 'procrastination' | 'boss_momentum' | 'streak_risk'
  final String title;
  final String message;
  final String? actionTarget;
  final String priority;

  const AiCoachNudge({
    required this.type,
    required this.title,
    required this.message,
    this.actionTarget,
    this.priority = 'normal',
  });

  factory AiCoachNudge.fromJson(Map<String, dynamic> json) {
    return AiCoachNudge(
      type: json['type'] as String? ?? 'general',
      title: json['title'] as String? ?? '',
      message: json['message'] as String? ?? '',
      actionTarget: json['actionTarget'] as String?,
      priority: json['priority'] as String? ?? 'normal',
    );
  }
}

/// Daily schedule proposal generated by AI Coach.
class DailyPlanProposal {
  final String date;
  final String summary;
  final List<String> schedule;
  final int targetXp;
  final int energyBudget;

  const DailyPlanProposal({
    required this.date,
    required this.summary,
    this.schedule = const [],
    this.targetXp = 0,
    this.energyBudget = 100,
  });

  factory DailyPlanProposal.fromJson(Map<String, dynamic> json) {
    final raw = json['data'] is Map<String, dynamic> ? json['data'] as Map<String, dynamic> : json;
    return DailyPlanProposal(
      date: raw['date'] as String? ?? '',
      summary: raw['summary'] as String? ?? raw['text'] as String? ?? '',
      schedule: (raw['schedule'] as List<dynamic>?)?.map((s) => s.toString()).toList() ?? [],
      targetXp: (raw['targetXp'] as num?)?.toInt() ?? 0,
      energyBudget: (raw['energyBudget'] as num?)?.toInt() ?? 100,
    );
  }
}

/// Weekly review summary synthesized by AI Coach.
class WeeklyReviewSummary {
  final String summary;
  final int completionRatePct;
  final int xpEarned;
  final int focusMinutes;
  final String reflection;

  const WeeklyReviewSummary({
    required this.summary,
    this.completionRatePct = 0,
    this.xpEarned = 0,
    this.focusMinutes = 0,
    required this.reflection,
  });

  factory WeeklyReviewSummary.fromJson(Map<String, dynamic> json) {
    final raw = json['data'] is Map<String, dynamic> ? json['data'] as Map<String, dynamic> : json;
    return WeeklyReviewSummary(
      summary: raw['summary'] as String? ?? raw['text'] as String? ?? '',
      completionRatePct: (raw['completionRatePct'] as num?)?.toInt() ?? 0,
      xpEarned: (raw['xpEarned'] as num?)?.toInt() ?? 0,
      focusMinutes: (raw['focusMinutes'] as num?)?.toInt() ?? 0,
      reflection: raw['reflection'] as String? ?? '',
    );
  }
}
